version: '3'

services:
    bot:
        build:
            context: ./
            target: production
        restart: unless-stopped
        tty: true
        env_file: ./.env
    db:
        image: postgres:12.2
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: muse
        ports:
            - '$EXPOSED_DB_PORT:5432'
    lavalink:
        image: fredboat/lavalink:latest
        restart: unless-stopped
        volumes:
            - ./.lavalink/application.yml:/opt/Lavalink/application.yml:ro
