version: '3'

services:
    bot:
        build:
            context: ./
            target: production
        restart: always
        tty: true
        env_file: ./.env
    db:
        image: postgres:12.2
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: muse
    lavalink:
        image: fredboat/lavalink:latest
        restart: always
        volumes:
            - ./.lavalink/application.yml:/opt/Lavalink/application.yml:ro
