version: '3'

services:
    bot:
        build:
            context: ../
            dockerfile: ./.docker/Dockerfile
            target: base
        tty: true
        command: yarn docker:start
        env_file: ../.env
        ports:
            - '$EXPOSED_API_PORT:3000'
        volumes:
            - ../:/opt/app
    db:
        image: postgres:12.2
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: muse
        ports:
            - '$EXPOSED_DB_PORT:5432'
    lavalink:
        image: fredboat/lavalink:latest
        volumes:
            - ../.lavalink/application.yml:/opt/Lavalink/application.yml:ro
