version: '3'

services:
    muse:
        build:
            context: .
            target: base
        tty: true
        command: yarn muse:docker:start
        env_file: ./.env
        ports:
            - '$EXPOSED_API_PORT:3000'
        volumes:
            - ./:/opt/app
        depends_on:
            - db
            - redis
            - lavalink
    radio:
        build:
            context: .
            target: base
        tty: true
        command: yarn radio:docker:start
        env_file: ./.env
        volumes:
            - ./:/opt/app
        depends_on:
            - db
            - redis
            - lavalink
    dashboard:
        build:
            context: .
            target: base
        tty: true
        command: yarn dashboard:docker:start
        env_file: ./.env
        ports:
            - '$EXPOSED_DASHBOARD_PORT:3000'
        volumes:
            - ./:/opt/app
    db:
        image: postgres:12.2
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: muse
        ports:
            - '$EXPOSED_DB_PORT:5432'
    lavalink:
        image: fredboat/lavalink:latest
        volumes:
            - ./.docker/lavalink.yml:/opt/Lavalink/application.yml:ro
    redis:
        image: redis
        ports:
            - '6379:6379'
    prometheus:
        image: prom/prometheus
        volumes:
            - ./.docker/prometheus.dev.yml:/etc/prometheus/prometheus.yml
        ports:
            - '$EXPOSED_PROM_PORT:9090'
