version: '3'

services:
    muse:
        image: ghcr.io/elysium-stack/muse:main
        restart: unless-stopped
        tty: true
        env_file: ./.env
        ports:
            - '$EXPOSED_API_PORT:3000'
        depends_on:
            - db
            - redis
            - lavalink
    radio:
        image: ghcr.io/elysium-stack/radio:main
        restart: unless-stopped
        tty: true
        env_file: ./.env
        ports:
            - '$EXPOSED_RADIO_PORT:3000'
        depends_on:
            - db
            - redis
            - lavalink
    db:
        image: postgres:12.2
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: muse
        ports:
            - '$EXPOSED_DB_PORT:5432'
    lavalink:
        image: ghcr.io/lavalink-devs/lavalink:latest
        restart: unless-stopped
        volumes:
            - ./.docker/lavalink.yml:/opt/Lavalink/application.yml:ro
    redis:
        image: redis
    prometheus:
        image: prom/prometheus
        restart: unless-stopped
        volumes:
            - ./.docker/prometheus.prod.yml:/etc/prometheus/prometheus.yml
