version: '3'

services:
    bot:
        build:
            context: .
            target: base
        tty: true
        command: yarn docker:start
        env_file: ./.env
        ports:
            - '$EXPOSED_API_PORT:3000'
        volumes:
            - ./:/opt/app
        depends_on:
            - db
            - lavalink
    db:
        image: postgres:12.2
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: muse
        ports:
            - '$EXPOSED_DB_PORT:5432'
    lavalink:
        image: fredboat/lavalink:latest
        volumes:
            - ./.docker/lavalink.yml:/opt/Lavalink/application.yml:ro
    prometheus:
        image: prom/prometheus
        volumes:
            - ./.docker/prometheus.dev.yml:/etc/prometheus/prometheus.yml
        ports:
            - '$EXPOSED_PROM_PORT:9090'
